## start 2_soil_temp block
sensor:
  - platform: rest
    resource: http://localhost/devices/69a7585768f3190aa42a11d7/sensors/temperatureSensor_5/value
    name: 2SOIL_TEMP_1/Soil Temperature Sensor 1
    unit_of_measurement: "°C"
  - platform: rest
    resource: http://localhost/devices/69a7585768f3190aa42a11d7/sensors/temperatureSensor_10/value
    name: 2SOIL_TEMP_1/Soil Temperature Sensor 2
    unit_of_measurement: "°C"
  - platform: rest
    resource: http://localhost/devices/69a7585768f3190aa42a11d7/sensors/analogInput_6/value
    name: 2SOIL_TEMP_1/Battery voltage
    unit_of_measurement: "Volts"
## end 2_soil_temp block