## start capacitive block
sensor:
  - platform: rest
    resource: http://localhost/devices/69aaa07b68f3190aa42a1206/sensors/temperatureSensor_0/value
    name: CAPACITIVE_3/Raw value from SEN0308
  - platform: rest
    resource: http://localhost/devices/69aaa07b68f3190aa42a1206/sensors/temperatureSensor_5/value
    name: CAPACITIVE_3/Soil Temperature Sensor
    unit_of_measurement: "°C"    
  - platform: rest
    resource: http://localhost/devices/69aaa07b68f3190aa42a1206/sensors/analogInput_6/value
    name: CAPACITIVE_3/Battery voltage
    unit_of_measurement: "Volts"
    
template:
  - sensor:
    - name: CAPACITIVE_3/soil value index
      state: >
        {% set raw = states('sensor.capacitive_2_raw_value_from_sen0308') | int(0) %}
        {% if raw < 0 %}
          {{ -1 }}
        {% else %}      
          {% set capacitive_sensor_dry_max = 500 %}
          {% set capacitive_sensor_n_interval = 6 %}
          {% set interval = (capacitive_sensor_dry_max / capacitive_sensor_n_interval) %}
          {% set idx = (raw / interval) | int %}
          {% if idx >= capacitive_sensor_n_interval %}
            {% set idx = capacitive_sensor_n_interval - 1 %}
          {% endif %}
          {{ (capacitive_sensor_n_interval - 1 - idx) }}
        {% endif %}
          
  - sensor:
    - name: CAPACITIVE_3/soil condition
      state: >
        {% set idx = states('sensor.capacitive_3_soil_value_index') | int(0) %}
        {% if idx == -1 %}
          no sensor         
        {% elif idx == 0 %}
          very dry
        {% elif idx == 1 %}
          dry     
        {% elif idx == 2 %}
          dry-wet   
        {% elif idx == 3 %}
          wet-dry   
        {% elif idx == 4 %}
          wet 
        {% else %}
          saturated
        {% endif %}
## end capacitive block
