## start co2 block
sensor:  
  - platform: rest
    resource: http://localhost/devices/69a7505f68f3190aa42a11c3/sensors/temperatureSensor_9/value
    name: CO2_1/CO2 ppm
    unit_of_measurement: "ppm"
  - platform: rest
    resource: http://localhost/devices/69a7505f68f3190aa42a11c3/sensors/temperatureSensor_7/value
    name: CO2_1/degree Celsius
    unit_of_measurement: "°C"
  - platform: rest
    resource: http://localhost/devices/69a7505f68f3190aa42a11c3/sensors/temperatureSensor_8/value
    name: CO2_1/relative humidity
    unit_of_measurement: "%RH"
  - platform: rest
    resource: http://localhost/devices/69a7505f68f3190aa42a11c3/sensors/temperatureSensor_5/value
    name: CO2_1/Soil Temperature Sensor
    unit_of_measurement: "°C"  
  - platform: rest
    resource: http://localhost/devices/69a7505f68f3190aa42a11c3/sensors/analogInput_6/value
    name: CO2_1/Battery voltage  
    unit_of_measurement: "Volts"
## end co2 block