## start loracam block
sensor:  
  - platform: rest
    resource: http://localhost/devices/69a7ff5f68f3190aa42a11eb/sensors/analogOutput_10/value
    name: LoRaCAM_AI_STATS_2EAA/number of packets
    unit_of_measurement: "pkt"   
  - platform: rest
    resource: http://localhost/devices/69a7ff5f68f3190aa42a11eb/sensors/analogOutput_11/value
    name: LoRaCAM_AI_STATS_2EAA/size in bytes
    value_template: "{{ value_json | multiply(1000) | round(0)}}"      
    unit_of_measurement: "bytes"  
  - platform: rest
    resource: http://localhost/devices/69a7ff5f68f3190aa42a11eb/sensors/analogOutput_12/value
    name: LoRaCAM_AI_STATS_2EAA/time on air
    unit_of_measurement: "min:sec"  
  - platform: rest
    resource: http://localhost/devices/69a7ff5f68f3190aa42a11eb/sensors/analogOutput_13/value
    name: LoRaCAM_AI_STATS_2EAA/luminosity  
    unit_of_measurement: ""

#from https://community.home-assistant.io/t/refresh-cached-images-in-lovelace-picture-elements-maybe-other-places-too/98351/18
camera:
  - platform: local_file
    name: LoRaCAM_AI_DEV_2DAA
    file_path: /config/www/loracam-ai/last-LoRaCAM_AI_DEV_2DAA-image.bmp
## end loracam block - leave CR at end of this line