## start tensiometer block
sensor:  
  - platform: rest
    resource: http://localhost/devices/69a8461e68f3190aa42a11f7/sensors/temperatureSensor_0/value
    name: TENSIOMETER_3/centibars from WM200
    unit_of_measurement: "cbar"   
  - platform: rest
    resource: http://localhost/devices/69a8461e68f3190aa42a11f7/sensors/temperatureSensor_1/value
    name: TENSIOMETER_3/resistance value from WM200
    value_template: "{{ value_json | multiply(10) | round(0)}}"      
    unit_of_measurement: "Ohms"  
  - platform: rest
    resource: http://localhost/devices/69a8461e68f3190aa42a11f7/sensors/temperatureSensor_5/value
    name: TENSIOMETER_3/Soil Temperature Sensor
    unit_of_measurement: "°C"  
  - platform: rest
    resource: http://localhost/devices/69a8461e68f3190aa42a11f7/sensors/analogInput_6/value
    name: TENSIOMETER_3/Battery voltage  
    unit_of_measurement: "Volts"

template:
  - sensor:
    - name: TENSIOMETER_3/soil value index
      state: >
        {% set cbar = states('sensor.tensiometer_3_centibars_from_wm200') | float(0) %}
        {% if cbar == 255 %}
          -1
        {% elif cbar == 240 %}
          -2         
        {% elif cbar > 100 %}
          0
        {% elif cbar > 60 %}
          1     
        {% elif cbar > 30 %}
          2   
        {% elif cbar > 10 %}
          4   
        {% else %}
          5
        {% endif %}
          
  - sensor:
    - name: TENSIOMETER_3/soil condition
      state: >
        {% set idx = states('sensor.tensiometer_3_soil_value_index') | int %}
        {% if idx == -2 %}
          sensor error          
        {% elif idx == -1 %}
          no sensor         
        {% elif idx == 0 %}
          very dry
        {% elif idx == 1 %}
          dry     
        {% elif idx == 2 %}
          dry-wet   
        {% elif idx == 3 %}
          wet-dry   
        {% elif idx == 4 %}
          wet 
        {% else %}
          saturated
        {% endif %}
## end tensiometer block


